### ISSUE TITLE
Event bugs

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#188]
Found a lot of bugs when trying to create and manage events.

```[tasklist]
### Tasks
- [x] Event dates are wrong on landing page (they seem to show weekday number, not date)
- [x] Event subtitle is required when creating an event
- [x] Event subtitle is probably unnecessary
- [x] Event link is required when creating an event
- [x] Searching for tag in selector and clicking on a tag doesn't clear the text input
- [x] Creating or editing an event yields a 404 not found when submitting (it redirects to /event/:id instead of /events/:id).
```

**Comment by fnurkla** [comment]
While I agree that the event subtitle shouldn't be required, I think that having it is a good thing. I think it works well for notifications and the like.

**Comment by fnurkla** [comment]
Subtitle did not seem necessary when I creating one on master just now.

**Comment by fnurkla** [comment]
Are we done with this? Or should we delete short description first?
