### ISSUE TITLE
Bookings page

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/web#23]
```[tasklist]
### Tasks
- [ ] Booking calendar
- [ ] Booking form
- [ ] Manage bookables
- [ ] https://github.com/Dsek-LTH/member-page/issues/1000
- [ ] https://github.com/Dsek-LTH/member-page/issues/883
- [ ] https://github.com/Dsek-LTH/member-page/issues/878
- [ ] https://github.com/Dsek-LTH/member-page/issues/877
```

**Comment by danieladugyan** [comment]
Something similar to dsek.se/booking, but I'm thinking we can design it along these lines instead:
- Replace booking table with a booking calendar.
- Color code the bookings the calendar.
- Maybe some way to only look at bookings for one item at a time.

Sketch (booking calendar imposed onto dsek.se/booking):
![Image](https://github.com/Dsek-LTH/web/assets/26229521/b4a6dddf-9053-493a-987c-4dbed1ee0fa9)
