### ISSUE TITLE
:zap: Build new webshop system

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/web#247]
This webshop epic is the conclusion of the discussion logged in #240.

The task lists track the overall completion of the webshop. The tasks are categorized into frontend and backend tasks. Each backend task, beyond the feature itself, also includes building schema models and adding tests.

```[tasklist]
- [x] (backend) notification system for grace period, reservations and queue
- [x] (backend) get available tickets for purchase (#251) (#252)
- [x] (frontend) tickets page where tickets are showed (#251) (#252)
- [x] (backend) add a ticket to cart (#253)
- [x] (backend) have a grace period on initial ticket launch, with queue system (#254) (#256)
```

```[tasklist]
### Cart
- [x] (frontend) cart page where cart is showed #287
- [x] (frontend) success page after purchase
- [x] (backend) notification system for purchase events
- [x] (backend) get cart items and pricing #257
- [x] (backend) purchase cart + stripe integration #257
- [x] (frontend) payment form connected to stripe #257
- [x] (backend) purchase and stripe error handling #257
```

```[tasklist]
### Tickets
- [x] (frontend) tickets admin page for managing tickets
- [x] (backend) manage tickets
- [x] (backend) ability to create tickets #258
- [x] (frontend) tickets creation page for creating new tickets #258
- [x] (frontend) ticket product page #280
```

```[tasklist]
### Purchased items
- [x] (frontend) user inventory where items are showed
- [x] (frontend) consumable page where QR-code is shown
- [ ] (frontend) event organizer page where tickets can be scanned and consumed
- [ ] (backend) ability to scan and consume a ticket
```

# Original description

Our current implementation, while working, is not really built around our workflow and is quite big in scope. It should be rebuilt for our two main use cases:

### Tickets
Paid and free events. Support for questions. Support for tickets with high demand, where priority should not depend (only) on user's connection, but instead a fairer system.

### Merch/goods
Again, both free and paid. Here it might be required for variants (such as for clothing, different sizes might have different stock). High demand is not required but might still be relevant.

For progress, I think these should be handled one-at-a-time, with tickets being prioritized. Try to keep the merch scenario in mind when developing, but do not do too much work.

For payment, either swish as now or stripe could be used. I think stripe is better due to issues with international students and swish.

**Comment by danieladugyan** [comment]
Closing this in favour of smaller backlog cards for remaining items.
