### ISSUE TITLE
Markdown pages (such as /cafe or /for-companies)

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/web#26]
```[tasklist]
### Tasks
- [ ] https://github.com/Dsek-LTH/web/issues/34
- [ ] https://github.com/Dsek-LTH/web/issues/35
- [x] Resolve markdown pages and display them
- [ ] Ability to add new markdown pages
```
