### ISSUE TITLE
:zap: Landing page

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#262]
```[tasklist]
### Tasks
- [x] Rounded corners (#199)
- [x] separate page for logged out users (#260)
- [ ] (moved) fix that calendar numbers are wrong (right now it shows the day in week, not day in month)
- [x] reconsider layout for logged in users (higher information density, remove hero image, info blurb and "for companies" button)
```
