### ISSUE TITLE
:zap: Photo archive

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#284]
```[tasklist]
### Tasks
- [ ] View single images
- [ ] CRUD images
- [ ] Browse image albums
- [ ] View image metadata
- [ ] Tag people à la `old.dsek.se`
- [ ] (Set image/tag as profile picture)
- [ ] Report image — if you don't like an image of yourself or the like
- [ ] Comments?
- [ ] Connect images to events?
- [ ] Allow users to submit images
```
```[tasklist]
### MinIO
- [ ] Access control
- [ ] Minio bucket for storage
- [ ] Filestash for management
```

**Comment by fnurkla** [comment]
After talking a bit with Oskar, we said that a Minio bucket will work well for our purposes. Image metadata will be in the database though.

**Comment by trettiofem** [comment]
Mockup: https://drive.google.com/drive/folders/1KZlu9F5ydpp2smTtDynj2tg0aXu7qVHJ?usp=drive_link
