### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/web#30]
```[tasklist]
### Tasks
- [ ] https://github.com/Dsek-LTH/web/pull/148
- [x] Send notifications, receive them
- [x] Send notifications on specific actions
- [x] Group notifications
- [ ] Push notifications
```

**Comment by Steindt** [comment]
- [ ] Notification bell and dropdown
- [ ] Send notifications, receive them
- [ ] Send notifications on specific actions
- [ ] Group notifications

**Comment by fnurkla** [comment]
@Steindt, are you taking the charge for the push notifications as well?

**Comment by Steindt** [comment]
Yes
