### ISSUE TITLE
Door admin page (edit door access)

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#40]
```[tasklist]
### Tasks
- [x] Create a page listing all doors
- [x] Create a door edit page
- [x] Add api for retrieving door access
- [x] Implement a form for adding door access policies
- [ ] https://github.com/Dsek-LTH/member-page/issues/1029
```
