### ISSUE TITLE
Add an awesome documentation page

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#414]
### Core Content
- [x] Tutorials: link to good tutorials for HTML, CSS, JS, TS, Tailwind, Svelte, Expo, Prisma, SQL, etc.
- [x] Guides: creating a new page, fixing a bug, modifying the database, style guide, design tips, setting up recommended VS Code extensions etc.
- [x] Reference: OpenAPI, folder structure, design tokens, global types, environment variables, external systems etc.
- [x] Explanation: tech stack, design libraries, design mobile first, goals of the project, etc.

### Other content
- [x] FAQ
- [x] Manifesto/testamente
- [x] History: screenshots/links to past versions, chronology of rewrite attempts, alumni?

### Original thoughts
The wiki is fine, but its main purpose is to be informative, not educational. If we want more members to be able to participate in development then we need really good guides to getting started.

- [x] Clean design.
- [x] Deployed on GitHub Pages.
- [ ] ~Embedded StackBlitz examples~.

https://diataxis.fr/
https://vitepress.dev/
https://github.com/jerrywu001/vitepress-plugin-sandpack

~**Blocked by lack of monorepo tooling**~
~https://astro.build/themes/details/starlight/~
~https://github.com/HiDeoo/starlight-openapi~
~https://kitdocs.vercel.app/~

```[tasklist]
### Tasks
- [ ] https://github.com/Dsek-LTH/web/pull/492
- [x] Add "Getting Started" guide
- [x] Add "Svelte" tutorial
- [x] Add "Environment variables" reference
- [x] Add "Tech stack" explanation
- [x] Add section for other content
- [x] Delete wiki
```
