### ISSUE TITLE
Add desktop version of nolla.nu

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#453]
The post-reveal nollning page has not been adapted to desktop screen sizes. Make the design responsive so that it looks decent at least at desktop sizes, without negatively impacting the mobile version of course.
```[tasklist]
### Tasks
- [x] Move navbar to top
- [x] reduce content width
- [x] mobile browser menu
- [x] make account drawer popup
```
