### ISSUE TITLE
Image posts

### ISSUE THREAD

**Issue by 03haax** [Dsek-LTH/web#498]
Much like creating news we should have a way to create image posts. Facebook equivalent:
![Image](https://github.com/user-attachments/assets/456d5001-de23-4cd9-8e76-9e5580816550)

```[tasklist]
### Tasks
- [x] Creation form (need some work)
- [x] Display one image
- [x] Upload images
- [x] Display many images
- [x] Edit event
- [ ] Move around image order
- [ ] Link to events
- [ ] Link to news
- [ ] Show on homepage
- [ ] Tag people/commities/places
- [ ] Integrate with archive
```
