### ISSUE TITLE
Documents page

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#83]
All the document pages are rather similar, as can be seen in our current folder structure in MinIO: 

```
Kravprofiler: kravprofiler/<år>/**/* ~[kravprofiler/<år>/<möte>/*]
SRD: 	      srd/<år>/**/*          ~[srd/<år>/<möte>/*]
Möten:	      <år>/**/*              ~[<år>/<möte>/*]
~roughly, as of 2023
```

This structure yields the following upload form:
1. Select document type
2. Select year
3. Select meeting
4. Input file name

Based on these choices, a file path is generated and displayed to user – perhaps we should allow overrides?
```[tasklist]
### Tasks
- [ ] https://github.com/Dsek-LTH/web/issues/132
- [ ] https://github.com/Dsek-LTH/web/issues/138
- [ ] https://github.com/Dsek-LTH/web/issues/144
- [x] Implement more general upload form
```

**Comment by danieladugyan** [comment]
Awaiting #120
