### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#86]
https://inlang.com/g/2fg8ng94/guide-nilsjacobsen-buildAGlobalSvelteApp
```[tasklist]
### Tasks
- [x] Implement translations for static content using paraglide.js
- [x] Implement translations for dynamic content in Prisma
- [ ] Translate all routes
```

**Comment by danieladugyan** [comment]
https://github.com/opral/monorepo/discussions/1807
https://github.com/LorisSigrist/paraglide-sveltekit-cookies

**Comment by danieladugyan** [comment]
https://developers.google.com/search/docs/specialty/international/localized-versions#all-method-guidelines
> Alternate URLs must be fully-qualified, including the transport method (http/https), so:
https://example.com/foo, not //example.com/foo or /foo

**Comment by danieladugyan** [comment]
Awaiting #120

**Comment by danieladugyan** [comment]
Closing this as completed. I'm sure we have still have some content left to translate, but we can open separate issues for that.
