### ISSUE TITLE
Sync mandates with keycloak

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#91]
```[tasklist]
### Tasks
- [x] On mandate CRUD, update keycloak group memberships
- [x] Ensure keycloak groups stay in sync with mandates by syncing regularly (one-way sync)
- [ ] Board members should also be added to dsek.styr group
- [ ] Create members from keycloak users?
```

How to schedule sync in SvelteKit:
```js
// hooks.server.ts:
import schedule from "node-schedule"
const job = schedule.scheduleJob('*/1 * * * *', function () {
console.log('This runs every minute')
})
```
