### ISSUE TITLE
Super admin - global alerts

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#92]
![Image](https://github.com/Dsek-LTH/web/assets/26229521/67588003-8b07-412e-a321-c1488dce7aee)

Admin interface
![Image](https://github.com/Dsek-LTH/web/assets/26229521/4d15e86d-ddb8-45b1-a2a7-2531214054a7)

```[tasklist]
### Tasks
- [x] add element to frontpage
- [x] create in database
- [x] create admin panel
- [x] adhere to language
- [x] limit access
- [x] connect to db
```
