### ISSUE TITLE
⚡Release

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#96]
```[tasklist]
### Tasks
- [ ] #186
- [ ] https://github.com/Dsek-LTH/web/issues/187
- [ ] https://github.com/Dsek-LTH/web/issues/201
- [ ] https://github.com/Dsek-LTH/web/issues/202
- [ ] https://github.com/Dsek-LTH/web/issues/204
```
